### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by VirusKA** [equinusocio/N1-Material#1]
Any documentation on how to add this to N1?

**Comment by equinusocio** [comment]
At the moment there is no theme. I'm a little busy and i'm stuk to the design process.

**Comment by GijsGoudzwaard** [comment]
You can add this to N1 but it won't update automatically.
Here's how it's done:

- Download a zip of this repo (or clone it) and unzip it
- Go to N1 > settings > General > Select theme > install theme
- Select the whole folder of N1-Material and let it wait for about 5 sec (it won't give any feedback until it's done, so don't panic that it's not working)

And you're done. After you've installed the theme it will activate automatically.
